---
- name: Establish some role-related facts
  ansible.builtin.set_fact:
    mongo_major_version: "{{ mongo_version[0:3] }}"

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
      - python3-pip
      - python3-dev
      - python3-setuptools
    state: present
    update_cache: true

- name: Install PyMongo from PIP
  ansible.builtin.pip:
    name: pymongo
    state: "{{ pymongo_pip_version is defined | ternary('present','latest') }}"
    version: "{{ pymongo_pip_version | default(omit) }}"

- name: Download MongoDB GPG key
  ansible.builtin.get_url:
    url: https://pgp.mongodb.com/server-8.0.asc
    dest: /tmp/server-8.0.asc
    mode: "0644"

- name: Create MongoDB keyring
  ansible.builtin.shell: |
    gpg --dearmor < /tmp/server-8.0.asc > /usr/share/keyrings/mongodb-server-8.0.gpg
  args:
    creates: /usr/share/keyrings/mongodb-server-8.0.gpg

- name: Configure MongoDB repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/mongodb-org-8.0.list
    content: |
      deb [ signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse
    mode: "0644"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install MongoDB
  ansible.builtin.apt:
    name: "{{ mongo_package_name }}"
    state: present
