---
# tasks file for mongodb

- name: Include playbook for mongo os confg
  include_tasks: prerequiste.yml 

- name: To install mongo on Debian
  include_tasks: debian.yml
  when:
    ansible_os_family == 'Debian'

- name: To install mongo on Redhat
  include_tasks: redhat.yml
  when:
    ansible_os_family == 'RedHat'
