---
# tasks file for mongodb

- name: Include playbook for mongo os configurations
  ansible.builtin.include_tasks: pre-requistes.yml

- name: To install mongo on Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: To install mongo on Redhat
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'
