---
- name: Configuring the MongoDB dns in /etc/hosts
  blockinfile:
    block: |
      {{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ item }}
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  become: true
  with_items:
    - "{{ groups['mongo'] }}"

- name: Setting up hostname of Mongo nodes
  hostname:
    name: "{{ inventory_hostname }}"
  become: true
