---

- name: Use different mongod.conf for auth initialization
  template:
    src: mongo_init_conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - mongodb_restart
    - wait_till_mongodb_started_on_localhost

- name: Flush all handlers at this point
  meta: flush_handlers

- name: Create root admin user
  mongodb_user:
    database: admin
    name: "{{ mongo_root_admin_name }}"
    password: "{{ mongo_root_admin_pwd }}"
    update_password: on_create
    roles: root
    state: present
  when: inventory_hostname in groups['mongo_master']
  run_once: true
  no_log: false 

- name: Create admin user
  mongodb_user:
    database: admin
    name: "{{ mongo_user_admin_name }}"
    password: "{{ mongo_user_admin_pwd }}"
    update_password: on_create
    roles: userAdminAnyDatabase
    state: present
  when: inventory_hostname in groups['mongo_master']
  run_once: true
  no_log: true

- name: Create backup root user
  mongodb_user:
    database: admin
    name: "{{ mongo_root_backup_name }}"
    password: "{{ mongo_root_backup_pwd }}"
    update_password: on_create
    roles: backup,clusterMonitor
    state: present
  when: inventory_hostname in groups['mongo_master']
  run_once: true
  no_log: true

- name: Create user defined users
  mongodb_user:
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: on_create
    roles: "{{ item.roles }}"
  with_items:
    - "{{ mongo_custom_users }}"
  run_once: true
  no_log: true
  when: inventory_hostname in groups['mongo_master'] and mongo_custom_users != "None"

- name: Move back mongod.conf
  template:
    src: mongo_conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - mongodb_restart
    - "{{ 'wait_till_mongodb_started' if replication_enabled == 'true' else 'wait_till_mongodb_started_on_localhost' }}"

- name: Flush all handlers at this point
  meta: flush_handlers
