---
# =============================================================================
# Check Root admin user Existance
# =============================================================================

- name: Check if root admin marker exists
  ansible.builtin.stat:
    path: /var/lib/mongodb/.mongodb_admin_created
  register: mongo_admin_marker

  when:
    - mongodb_master_group in groups
    - inventory_hostname in groups[mongodb_master_group]

  
# =============================================================================
# MongoDB Users Setup — HA Users
# =============================================================================
- name: Create root admin user
  community.mongodb.mongodb_user:
    database: admin
    name: "{{ mongo_root_admin_name }}"
    password: "{{ mongo_root_admin_pwd }}"
    update_password: on_create
    roles: root
    state: present
    create_for_localhost_exception: /var/lib/mongodb/.mongodb_admin_created

  when:
    - mongodb_master_group in groups
    - inventory_hostname in groups[mongodb_master_group]
    - not mongo_admin_marker.stat.exists

  
  no_log: false

# =============================================================================
# User Admin
# =============================================================================

- name: Create user admin
  community.mongodb.mongodb_user:
    database: admin
    name: "{{ mongo_user_admin_name }}"
    password: "{{ mongo_user_admin_pwd }}"
    update_password: on_create
    roles: userAdminAnyDatabase
    state: present

    login_user: "{{ mongo_root_admin_name }}"
    login_password: "{{ mongo_root_admin_pwd }}"
    login_database: admin
  when:
  - mongodb_master_group in groups
  - inventory_hostname in groups[mongodb_master_group]
  - mongodb_authentication_enabled | default(true)

  
  no_log: false

# =============================================================================
# Backup User
# =============================================================================

- name: Create backup root user
  community.mongodb.mongodb_user:
    database: admin
    name: "{{ mongo_root_backup_name }}"
    password: "{{ mongo_root_backup_pwd }}"
    update_password: on_create
    roles:
      - backup
      - clusterMonitor
    state: present

    login_user: "{{ mongo_root_admin_name }}"
    login_password: "{{ mongo_root_admin_pwd }}"
    login_database: admin
  when:
  - mongodb_master_group in groups
  - inventory_hostname in groups[mongodb_master_group]
  - mongodb_authentication_enabled | default(true)

  
  no_log: false
