---
- name: reload_systemd
  systemd:
    daemon_reload: "yes"

- name: mongodb_restart
  service:
    name: "{{ mongo_service_name }}"
    state: restarted

- name: wait_till_mongodb_started
  wait_for:
    host: "{{ item }}"
    port: "{{ mongo_port }}"
    timeout: 120
  with_items:
    - "{{ groups['mongo_master'] | list }}"
    - "{{ groups['mongo_slave'] | list }}"

- name: wait_till_mongodb_started_on_localhost
  wait_for:
    host: "127.0.0.1"
    port: "{{ mongo_port }}"
    delay: 5
    timeout: 120
