- name: reload_systemd
  systemd:
    daemon_reload: "yes"

- name: mongodb_restart
  service:
    name: "{{ mongo_service_name }}"
    state: restarted

# ------------------------------------------
#    (Runs on remote host, NOT localhost!)
# ------------------------------------------
- name: Check if MongoDB is already listening on 127.0.0.1
  shell: ss -ltnp | grep 127.0.0.1:{{ mongo_port }}
  register: mongo_port_check_local
  ignore_errors: true
  changed_when: false

- name: Debug message if MongoDB is already running
  debug:
    msg: "MongoDB is already running on {{ inventory_hostname }}:{{ mongo_port }}, skipping wait."
  when: mongo_port_check_local.rc == 0

- name: Wait for MongoDB to be ready on 127.0.0.1 if not already listening
  wait_for:
    host: "127.0.0.1"
    port: "{{ mongo_port }}"
    delay: 5
    timeout: 60
  when: mongo_port_check_local.rc != 0
