--- 

- name: Create a replicaset and use a custom priority for each member
  community.mongodb.mongodb_replicaset:
    login_host: "{{ ansible_eth0.ipv4.address }}"
    replica_set: "{{ replica_set }}"
    arbiter_at_index: 2
    members:
    - host: "{{ mongo_master }}:{{ port }}"
      priority: 1
    - host: "{{ mongo_slave1 }}:{{ port }}"
      priority: 0.5
    - host: "{{ mongo_slave2 }}:{{ port }}"
      priority: 0
  when: inventory_hostname in groups['master']

- name: Secondary Slave OK
  community.mongodb.mongodb_shell:
    login_host: "{{ ansible_eth0.ipv4.address }}"
    eval: "rs.slaveOk()"
  when: inventory_hostname in groups['secondary']
